Repository Nouuu/Boissibook, pull requests merged in 2022-05, with the labels that each got.

#1 setup CQS and remove comment
  src/main/java/org/esgi/boissibook/features/user/domain/UserCommandHandler.java
  src/main/java/org/esgi/boissibook/features/user/domain/UserQueryHandler.java
  src/main/java/org/esgi/boissibook/features/user/domain/UserService.java
  src/main/java/org/esgi/boissibook/features/user/infra/config/SpringUserBeans.java
  src/main/java/org/esgi/boissibook/features/user/infra/web/UserController.java
Labels: enhancement

#26 Ajout de la définition API de la partie readlist
  src/main/java/org/esgi/boissibook/features/readlist/domain/BookReview.java
  src/main/java/org/esgi/boissibook/features/readlist/domain/ReadingStatus.java
  src/main/java/org/esgi/boissibook/features/readlist/domain/Visibility.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/repository/BookReviewEntity.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/ReadlistController.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/request/CommentRequest.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/request/CreateBookReviewRequest.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/request/ProgressRequest.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/request/ReviewRequest.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/request/StatusRequest.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/request/UpdateBookReviewRequest.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/response/BookReviewIdResponse.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/response/BookReviewResponse.java
  src/main/java/org/esgi/boissibook/features/readlist/infra/web/response/BookReviewsResponse.java
  src/main/java/org/esgi/boissibook/features/user/infra/web/UserCommandController.java
  src/main/java/org/esgi/boissibook/infra/validation/.gitkeep
Labels: documentation

#57 remove "/" needed before query param
  src/main/java/org/esgi/boissibook/features/book_search/infra/web/BookSearchRequestController.java
Labels: bug
